name: MalawiAquaticUnion
favicon: null
layout_spectrum: 0.5743531018961221
typography_spectrum: 0.5802050228230655
title: Malawi Aquatic Union MAU
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7d0d5'
    - '#201f27'
    - '#949188'
    - '#c85e4e'
    - '#a1180e'
  brandStrength: 0.16753461444750428
  lightness: 0.6578276851214468
  saturation: 0.570532645797357
  rhythmicContrast: 0.7669760938733816
purpose: []
